# Generated by Django 5.0.3 on 2024-03-07 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500, verbose_name='Питання')),
                ('is_show', models.BooleanField(default=True, verbose_name='Відображати')),
                ('score_value', models.IntegerField(default=1, verbose_name='Кількість балів')),
            ],
            options={
                'verbose_name': 'Питання',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
            ],
            options={
                'verbose_name': 'Вікторина',
                'verbose_name_plural': 'Вікторини',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500, verbose_name='Варіант відповіді')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильна відповідь')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.question')),
            ],
            options={
                'verbose_name': 'Відповідь',
                'verbose_name_plural': 'Відповіді',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Quiz.quiz')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результати',
            },
        ),
    ]
