# Generated by Django 5.0.3 on 2024-03-07 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_alter_question_options_remove_question_is_show_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 3, 7, 12, 43, 52, 631154), verbose_name='Час створення'),
        ),
    ]
