# Generated by Django 5.0.3 on 2024-03-08 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_alter_quiz_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'відповідь', 'verbose_name_plural': 'відповіді'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'питання', 'verbose_name_plural': 'питання'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'вікторину', 'verbose_name_plural': 'вікторини'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'результат', 'verbose_name_plural': 'результати'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now, verbose_name='Час створення'),
        ),
    ]
