# Generated by Django 5.0.3 on 2024-03-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('tg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tg_username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('instagram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('mail_address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
