# Generated by Django 5.0.3 on 2024-03-08 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'абітурієнт', 'verbose_name_plural': 'абітурієнти'},
        ),
        migrations.AddField(
            model_name='tguser',
            name='registered',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Нікнейм в Instagram'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='mail_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пошта'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ПІБ'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Ідентифікатор'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Нікнейм в Telegram'),
        ),
    ]
