# Generated by Django 5.0.3 on 2024-03-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGBot', '0002_alter_tguser_options_tguser_registered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='Пріорітет відображення')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Рисунок')),
            ],
            options={
                'verbose_name': 'слайд',
                'verbose_name_plural': 'слайди',
            },
        ),
    ]
