# Generated by Django 5.0.3 on 2024-03-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGBot', '0004_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tmp_blocks/', verbose_name='Рисунок')),
                ('description', models.CharField(max_length=200, verbose_name='Підпис')),
                ('template_type', models.CharField(choices=[('START', 'СТАРТ'), ('CONTACTS', 'КОНТАКТИ'), ('FACULTY', 'ФАКУЛЬТЕТ'), ('SPECIALTY', 'СПЕЦІАЛЬНОСТІ'), ('QUIZ', 'Вікторини')], max_length=20, verbose_name='Тип шаблону')),
            ],
            options={
                'verbose_name': 'шаблон',
                'verbose_name_plural': 'шаблони',
            },
        ),
    ]
