# Generated by Django 5.0.3 on 2024-03-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGBot', '0005_templateblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateblock',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Підпис'),
        ),
        migrations.AlterField(
            model_name='templateblock',
            name='template_type',
            field=models.CharField(choices=[('START', 'СТАРТ'), ('CONTACTS', 'КОНТАКТИ'), ('FACULTY', 'ФАКУЛЬТЕТ'), ('SPECIALTY', 'СПЕЦІАЛЬНОСТІ'), ('QUIZ', 'ВІКТОРИНИ')], max_length=20, verbose_name='Тип шаблону'),
        ),
    ]
