# Generated by Django 5.0.3 on 2024-03-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGBot', '0007_alter_templateblock_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tmp_blocks/', verbose_name='Рисунок'),
        ),
    ]
