# Generated by Django 5.0.3 on 2024-03-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGBot', '0008_alter_templateblock_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateblock',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Підпис'),
        ),
    ]
