# Generated by Django 5.0.3 on 2024-03-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGBot', '0010_alter_templateblock_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateblock',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='Підпис'),
        ),
    ]
