# Generated by Django 5.0.3 on 2024-03-15 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TGBot', '0012_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TGBot.tguser', verbose_name='Адміністратор'),
        ),
    ]
